# permissions for end users to edit scalemons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scalemon-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scalemon-ops
    app.kubernetes.io/part-of: scalemon-ops
    app.kubernetes.io/managed-by: kustomize
  name: scalemon-editor-role
rules:
- apiGroups:
  - monitoring.stompy.io
  resources:
  - scalemons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.stompy.io
  resources:
  - scalemons/status
  verbs:
  - get
